### ISSUE TITLE
Please show me how to use it. I don't see any .exe file to run?

### ISSUE THREAD

**Issue by nonamebatbai** [ReYaNOW/OCRHelper#1]
Please show me how to use it. I don't see any .exe file to run?

**Comment by ReYaNOW** [comment]
Hello!
You can download .7z archives which contains .exe file from releases section
But for now it will not work correctly on other people's PCs
I will have to make another binary file with some changes which will work (sorry for that)

**Comment by ReYaNOW** [comment]
@nonamebatbai Now it should work
You can download it from here https://github.com/ReYaNOW/OCRHelper/releases
But unfortunately there is no English language support at the moment and I will add it as soon as possible.
